---
- name: "Packages: Install packages"
  community.general.pkgng:
    name: "{{ freebsd_bash_install_packages }}"
  register: result
  until: result is succeeded
  retries: "{{ freebsd_bash_install_retries }}"
  delay: "{{ freebsd_bash_install_delay }}"

- name: "Packages: Debug freebsd_bash_debug={{ freebsd_bash_debug }}"
  ansible.builtin.debug:
    var: result
  when: freebsd_bash_debug | bool

# EOF
