---
- name: Install packages
  pkgng:
    name: "{{ freebsd_bash_install_packages }}"
  register: result
  retries: "{{ freebsd_bash_install_retries }}"
  until: result is succeeded
  delay: "{{ freebsd_bash_install_delay }}"
