---

- name: "packages: Install packages"
  community.general.pkgng:
    name: "{{ freebsd_bash_install_packages }}"
  register: result
  until: result is succeeded
  retries: "{{ freebsd_bash_install_retries }}"
  delay: "{{ freebsd_bash_install_delay }}"

- name: "packages: Debug"
  ansible.builtin.debug:
    var: result
  when: freebsd_bash_debug|bool

# EOF
...
