---
- name: "User: Change default shell to /usr/local/bin/bash"
  ansible.builtin.user:
    name: "{{ item }}"
    shell: /usr/local/bin/bash
  register: result
  loop: "{{ freebsd_bash_users }}"

- name: "User: Debug freebsd_bash_debug={{ freebsd_bash_debug }}"
  ansible.builtin.debug:
    var: result
  when: freebsd_bash_debug | bool

# EOF
